CarWash/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('insumos/', insumos, name="insumos"),
    path('modificar_insumo/<id>/', modificar_insumo, name="modificar_insumo"),
    path('eliminar_insumo/<id>/', eliminar, name="eliminar_insumo"),
    path('mision/', mision, name="mision"),
    path('registro/', registro, name="registro"),
]

carWash_dj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator


# Create your models here.


# Servicio: simple, gold, premiun -> (Producto)
class Servicio(models.Model):

    nombre = models.CharField(max_length=30)
    precio = models.IntegerField()
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="servicios", null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicio"


class Slider(models.Model):

    nombre = models.CharField(max_length=30)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="slider", null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Slider"
        verbose_name_plural = "Slider"


class Galeria(models.Model):

    nombre = models.CharField(max_length=30)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to="galeria", null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Galeria"
        verbose_name_plural = "Galeria"


class Mision(models.Model):

    nombre = models.CharField(max_length=30)
    descripcion = models.TextField(max_length=200, blank=True,
                                   help_text="Escriba un mensaje para\
                                   mostrar en la seccion de Mision\
                                   del sitio web")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Mision"
        verbose_name_plural = "Mision"


class Vision(models.Model):

    nombre = models.CharField(max_length=30)
    descripcion = models.TextField(max_length=200, blank=True,
                                   help_text="Escriba un mensaje para\
                                   mostrar en la seccion de Vision\
                                   del sitio web")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Vision"
        verbose_name_plural = "Vision"


opciones_consulta = [
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"]
]


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    telefono = models.IntegerField()
    email = models.EmailField()
    opciones_consulta = models.IntegerField(choices=opciones_consulta,
                                            name="motivo")
    mensaje = models.TextField()
    recibir_ofertas = models.BooleanField(name="ofertas",
                                          help_text="Reciba nuestras ofertas\
                                              exclusivas!")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Contacto"
        verbose_name_plural = "Contacto"


# Insumo must be handled outside of Django Admin


'''class Insumo(models.Model):

    nombre = models.CharField(validators=[MinLengthValidator(
                                limit_value=3,
                                message='Minimo 3 carácteres!')],
                              max_length=120)
    precio = models.IntegerField()
    imagen = models.ImageField(upload_to="insumo", null=True)
    descripcion = models.TextField(validators=[MinLengthValidator(
                                limit_value=3,
                                message='Minimo 3 carácteres!')],
                              max_length=200)
    stock = models.IntegerField()

    def __str__(self):
        return self.nombre
'''

app/forms.py
from django import forms
from .models import Contacto


class ContactoForm(forms.ModelForm):
    """
        Form Contacto
    """

    """nombre = forms.CharField(required=True,
                             min_length=3,
                             max_length=80,
                             widget=forms.TextInput(attrs={
                                        'class': 'form-control',
                                        'pattern': '[A-Za-z ]+',
                                        'title': 'Debe contener solo letras!'
                                    }
                                )
                             )
    """
    class Meta:

        model = Contacto
        fields = '__all__'

app/views.py
from django.shortcuts import render
from .models import Servicio, Slider, Galeria, Mision, \
    Vision, Contacto
from .forms import ContactoForm

# Create your views here.


def home(request):
    # fetch all Servicios objects into a list[]
    servicios = Servicio.objects.all()
    fotos_slider = Slider.objects.all()

    # store into data{} all Servicio's objects
    # and render it to django template "Home"
    data = {
        'servicios': servicios,  # key:'servicios' could be any name
        'slider': fotos_slider
    }
    return render(request, 'app/home.html', data)  # data as a third param


def contacto(request):
    # if form Contacto is empty(template) it'll be sent right back here
    data = {
        'form': ContactoForm()  # Instantiating a new empty form
    }

    # POST indicates a form with data was submit
    # POST is a dict with data
    if request.method == 'POST':
        # store Contacto form data into this var
        formulario = ContactoForm(data=request.POST)

        if formulario.is_valid():
            formulario.save()
            data["mensaje"] = "Contacto enviado! :)"

        data["form"]: formulario

    return render(request, 'app/contacto.html', data)


def mision(request):

    fotos_galeria = Galeria.objects.all()
    mision = Mision.objects.all().first()
    vision = Vision.objects.all().first()
    data = {
        'galeria': fotos_galeria,
        'mision': mision,
        'vision': vision
    }
    return render(request, 'app/mision.html', data)

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Bienvenido a Car Wash">
    <title>Car Wash |{% block title %}{% endblock %}</title>
    
    {# Bootstrap #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

   
    {# load css main file #}
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
    <link rel="icon" href="{% static 'app/img/car.png' %}">

    {% block plugins %}
    {% endblock %}


</head>
<body>
    {# sera heredado #}
    <header id="header">
        
        <img src="{% static 'app/img/menuiconwhite.png' %}" alt="menu" class="menu" id="menu">
        
        <div class="contenedor_logo">
            
            <img src="{% static 'app/img/logo.png' %}" alt="logo" class="logo">
            
            <div id="contenedor_feriado">
                <p>Proximo feriado</p>
                <p id="feriado"></p>
            </div>
        
        </div>
        
        <div>
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li>
                        <a href="{% url 'mision' %}">Quienes Somos</a>
                    </li>
                    <li>
                        <a href="#">Iniciar Sesion</a>
                    </li>
                    
                </ul>
            </nav>
        </div>

    </header>

    <div id="contenido" class="container">
        {% block contenido %}
        {% endblock  %}
    </div>

    {# sera heredado #}
    <footer>
        <div>
			<nav>
				<ul>
                    <li>
                        <span>Copyright 2020 © Todos Los Derechos Reservados </span> |
                    </li>
                    <li>
                        <a href="{% url 'home' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li>
                        <a href="{% url 'mision' %}">Quienes Somos</a>
                    </li>
				</ul>
			</nav>
        </div>
    </footer>

    {# sera heredado #}
    <!--JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    

    <script src="{% static 'app/js/menu.js' %}"></script>
    <script src="{% static 'app/js/feriados.js' %}"></script>
    
    {# all js files located at bottom DOM not included in base.template #}
    {% block js %}
    {% endblock %}


</body>
</html>

app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block title %}Contacto{% endblock %}

{% load static %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    {% if mensaje %}
    <div>
        {% for m in mensaje %}
            <script>
                Swal.fire({
                    "title": "Felicidades",
                    "text": "{{mensaje}}",
                    "icon": "success"
                })
            </script>
        {% endfor %}
    </div>
    {% endif %}

{% endblock %}

{% block contenido %}

    {% load crispy_forms_tags %}
    <br>
    <br>
    <div class="row">
        <div class="col-12 col-md-6 offset-md-3">
            <div class="card">
                <div class="card-body">
                    <h2>Contáctanos!</h2>
                    <hr>
                    {# if action button is empty, form data will be sent back to views.py #}
                    {# IMPORTANT! POST method allows not to reveal data on URL web browser #}
                    <form action="" method="post" >
                        
                        {% csrf_token %}
                        {{ form | crispy }}

                        <br>
                        <div class="d-flex justify-content-end">
                            <button type="reset" class="btn btn-secondary">Cancelar</button>
                            &nbsp;
                            <button type="submit" class="btn btn-primary">Enviar</button>
                        </div>
                    </form>
                    <h5>{{ mensaje }}</h5>
                    <br>
                    <br>
                    <div id="div-map" >
                        <iframe id="map" style="border-radius: 10px;"src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3329.580040353405!2d-70.6073551842025!3d-33.43419160406545!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662cf76b85e6d93%3A0xdfa78e8e5c1839b2!2sAv.%20Ricardo%20Lyon%201498%2C%20Providencia%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses!2scl!4v1601004464217!5m2!1ses!2scl" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                    </div>
                </div>
            </div>
        <div>
    </div>
    
    
    
	
{% endblock  %}

app/templates/app/index.html
{% extends 'app/base.html' %}

{% block title %}
 - Inicio
{% endblock %}

{% load static %}

{% block js %}

<!--Slider script-->
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<script>
    $(document).ready(function(){
        $('.slider').bxSlider({
            auto: true,
            pause: 2000,
            mode:'fade',
             
        });
    });
</script>

{% endblock %}

{% block css %}

<!--Silder Plug-in-->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">

{% endblock %}

{% block contenido %}

<!--*********** SLIDER **************-->
<div class="slider">
    {% for s in sliders %}
    <div>
        {% if s.imagen %}
        <img class="banner" src="{{ s.imagen.url }}" alt="">
        {% endif %}
    </div>
    {% endfor %}
</div>

<!---------------------Servicios-------------------------->
{% load humanize %}
<div class="servicios">

    {% for s in servicios %}
    <div class="servicio">
        <div class="contenedor_servicio">
            {% if s.imagen %}
            <img src="{{ s.imagen.url }}" alt="">
            {% endif %}

            <div class="detalle">
                <h2>{{ s.nombre | capfirst }}</h2>
                <h3>Desde ${{ s.precio | intcomma }}</h3>
            </div>
        </div>
    </div>
    {% endfor %}

</div>

<!---------------------Resenas de Clientes-------------------------->
<div class="resenas">
    
    <div class="resena">
        <div class="resena-text">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Corrupti enim voluptatibus rerum architecto.
        </div>
        
        <p>Lorem ipsum</p>
    </div>

    <div class="resena">
        <div class="resena-text">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit.
            Corrupti enim voluptatibus rerum architecto.
        </div>
        <p>Lorem ipsum</p>
    </div>

    <div class="resena">
        <div class="resena-text">
            Oink ipsum, dolor sit amet consectetur adipisicing elit.
            Corrupti enim voluptatibus rerum architecto.
        </div>
        <p>Lorem ipsum</p>
    </div>
</div>

{% endblock %}

app/templates/app/insumos.html
{% extends 'app/base.html' %}

{% block title %}
 - Insumos
{% endblock %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

{% if messages %}
<div>
    {% for message in messages %}
        <script>
            Swal.fire({
                "title": "Feliciades",
                "text": "{{message}}",
                "icon": "success"
            })
        </script>
    {% endfor %}
</div>
{% endif %}

<script>
    function eliminar(id) {
        Swal.fire({
                "title": "¿Está seguro?",
                "text": "Esta acción no se podra deshacer",
                "icon": "warning",
                "confirmButtonText": "Si, eliminar",
                "cancelButtonText": "No, cancelar",
                "showCancelButton": true
            })
            .then(function(result) {
                if (result.isConfirmed) {
                    window.location.href = "/eliminar_insumo/"+id+"/"
                }
            })
    }
</script>

{% endblock %}

{% block contenido %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        {% load crispy_forms_tags %}
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}

            <div class="d-flex justify-content-center">
                <input class="btn btn-primary btn-sm" type="submit" id="guardar_i" value="Guardar">
                &nbsp;
                <input class="btn btn-secondary btn-sm" type="reset" value="Limpiar">
            </div>
        </form>
    </div>
</div>

{% if perms.app.view_insumo %}
<h2>Listado de insumos</h2>
<table class="table table-striped table-hover table-responsive-sm" id="pagtable">
    <tr>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Imagen</th>
        <th>Descripción</th>
        <th>Stock</th>
        {% if perms.app.change_insumo or perms.app.delete_insumo %}
        <th>Opciones</th>
        {% endif %}
    </tr>
    {% for i in entity %}
    <tr>
        <td> {{ i.nombre }} </td>
        <td> {{ i.precio }} </td>
        <td> {{ i.imagen }} </td>
        <td> {{ i.descripcion }} </td>
        <td> {{ i.stock }} </td>
        {% if perms.app.change_insumo or perms.app.delete_insumo %}
        <td>
            {% if perms.app.change_insumo %}
            <a class="btn btn-primary btn-sm" href="{% url 'modificar_insumo' i.id %}">Modificar</a>
            {% endif %}
            {% if perms.app.delete_insumo %}
            <a class="btn btn-danger btn-sm" href="#" onclick="eliminar({{ i.id }})">Eliminar</a>
            {% endif %}
        </td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% include 'app/paginator.html' %}

{% endif %}

{% endblock %}

app/templates/app/mision.html
{% extends 'app/base.html' %}

{% block title %}Quienes Somos{% endblock %}

{% load static %}

{% block plugins %}

    {# Fancy Box #}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />

{% endblock %}

{% block contenido %}
    
    {# Mision #}
    {# Implementar singleton a nivel de modelo#}
    {% if mision.descripcion %}
        <blockquote>
            {{ mision.descripcion }}
            <span>Misión</span>
        </blockquote>
    {% else %}
            <blockquote>
                Car Wash!
                <span>Misión</span>
            </blockquote>
    {% endif %}    
    
    {# Vision #}
    {% if vision.descripcion %}
            <blockquote>
                {{ vision.descripcion }}
                <span>Visión</span>
            </blockquote>
        {% else %}
                <blockquote>
                    Car Wash!
                    <span>Visión</span>
                </blockquote>
        {% endif %}

    {# Galeria #}
    <div class="galeria">
        {% for g in galeria %}
            {% if  g.imagen %}
                <a data-fancybox="gallery" href="{{ g.imagen.url }} ">
                    <img src="{{ g.imagen.url }} ">
                </a>
            {% endif %}
        {% endfor %}
    </div>

{% endblock  %}

{% block js %}

    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

{% endblock %}

app/templates/app/modificar_insumo.html
{% extends 'app/base.html' %}

{% block title %}
 - Modificar Insumo
{% endblock %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
{% endblock %}

{% block contenido %}

<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        {% load crispy_forms_tags %}
        <form method='post' enctype="multipart/form-data">
            {% csrf_token %}
            {{ form | crispy }}

            <input class="btn btn-primary" type="submit" value="Modificar">
            <input class="btn btn-secondary" type="reset" value="Limpiar">
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}